name: CI
on:
  pull_request:
    branches: master
jobs:
  release:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - run: yarn install

      - run: yarn lint

      - run: yarn test
